package com.hdya.imagetagging.utils

object PinyinUtils {
    
    /**
     * Convert Chinese characters to Pinyin for search
     * This is a simplified implementation that covers common Chinese characters
     */
    private val chineseToPinyin = mapOf(
        '的' to listOf("de"),
        '是' to listOf("shi"),
        '我' to listOf("wo"),
        '你' to listOf("ni"),
        '他' to listOf("ta"),
        '她' to listOf("ta"),
        '它' to listOf("ta"),
        '了' to listOf("le"),
        '在' to listOf("zai"),
        '有' to listOf("you"),
        '和' to listOf("he"),
        '人' to listOf("ren"),
        '这' to listOf("zhe"),
        '中' to listOf("zhong"),
        '大' to listOf("da"),
        '为' to listOf("wei"),
        '上' to listOf("shang"),
        '个' to listOf("ge"),
        '国' to listOf("guo"),
        '时' to listOf("shi"),
        '要' to listOf("yao"),
        '就' to listOf("jiu"),
        '出' to listOf("chu"),
        '会' to listOf("hui"),
        '可' to listOf("ke"),
        '也' to listOf("ye"),
        '你' to listOf("ni"),
        '对' to listOf("dui"),
        '生' to listOf("sheng"),
        '能' to listOf("neng"),
        '而' to listOf("er"),
        '子' to listOf("zi"),
        '那' to listOf("na"),
        '得' to listOf("de"),
        '于' to listOf("yu"),
        '着' to listOf("zhe"),
        '下' to listOf("xia"),
        '自' to listOf("zi"),
        '之' to listOf("zhi"),
        '年' to listOf("nian"),
        '过' to listOf("guo"),
        '发' to listOf("fa"),
        '后' to listOf("hou"),
        '作' to listOf("zuo"),
        '里' to listOf("li"),
        '用' to listOf("yong"),
        '道' to listOf("dao"),
        '行' to listOf("xing"),
        '所' to listOf("suo"),
        '然' to listOf("ran"),
        '家' to listOf("jia"),
        '种' to listOf("zhong"),
        '事' to listOf("shi"),
        '方' to listOf("fang"),
        '多' to listOf("duo"),
        '经' to listOf("jing"),
        '么' to listOf("me"),
        '去' to listOf("qu"),
        '法' to listOf("fa"),
        '学' to listOf("xue"),
        '如' to listOf("ru"),
        '水' to listOf("shui"),
        '前' to listOf("qian"),
        '面' to listOf("mian"),
        '又' to listOf("you"),
        '定' to listOf("ding"),
        '做' to listOf("zuo"),
        '从' to listOf("cong"),
        '还' to listOf("hai"),
        '因' to listOf("yin"),
        '当' to listOf("dang"),
        '两' to listOf("liang"),
        '点' to listOf("dian"),
        '期' to listOf("qi"),
        '问' to listOf("wen"),
        '小' to listOf("xiao"),
        '部' to listOf("bu"),
        '其' to listOf("qi"),
        '些' to listOf("xie"),
        '主' to listOf("zhu"),
        '样' to listOf("yang"),
        '理' to listOf("li"),
        '心' to listOf("xin"),
        '她' to listOf("ta"),
        '本' to listOf("ben"),
        '前' to listOf("qian"),
        '开' to listOf("kai"),
        '但' to listOf("dan"),
        '因' to listOf("yin"),
        '只' to listOf("zhi"),
        '从' to listOf("cong"),
        '想' to listOf("xiang"),
        '实' to listOf("shi"),
        '日' to listOf("ri"),
        '国' to listOf("guo"),
        '们' to listOf("men"),
        '我' to listOf("wo"),
        '到' to listOf("dao"),
        '说' to listOf("shuo"),
        '时' to listOf("shi"),
        '以' to listOf("yi"),
        '于' to listOf("yu"),
        '人' to listOf("ren"),
        '有' to listOf("you"),
        '来' to listOf("lai"),
        '一' to listOf("yi"),
        '上' to listOf("shang"),
        '也' to listOf("ye"),
        '就' to listOf("jiu"),
        '进' to listOf("jin"),
        '关' to listOf("guan"),
        '什' to listOf("shen"),
        '二' to listOf("er"),
        '无' to listOf("wu"),
        '现' to listOf("xian"),
        '表' to listOf("biao"),
        '间' to listOf("jian"),
        '手' to listOf("shou"),
        '应' to listOf("ying"),
        '明' to listOf("ming"),
        '高' to listOf("gao"),
        '王' to listOf("wang"),
        '长' to listOf("chang"),
        '看' to listOf("kan"),
        '提' to listOf("ti"),
        '系' to listOf("xi"),
        '相' to listOf("xiang"),
        '知' to listOf("zhi"),
        '三' to listOf("san"),
        '已' to listOf("yi"),
        '老' to listOf("lao"),
        '由' to listOf("you"),
        '十' to listOf("shi"),
        '很' to listOf("hen"),
        '给' to listOf("gei"),
        '名' to listOf("ming"),
        '太' to listOf("tai"),
        '通' to listOf("tong"),
        '四' to listOf("si"),
        '五' to listOf("wu"),
        '六' to listOf("liu"),
        '七' to listOf("qi"),
        '八' to listOf("ba"),
        '九' to listOf("jiu"),
        '十' to listOf("shi"),
        '百' to listOf("bai"),
        '千' to listOf("qian"),
        '万' to listOf("wan"),
        '亿' to listOf("yi"),
        '东' to listOf("dong"),
        '西' to listOf("xi"),
        '南' to listOf("nan"),
        '北' to listOf("bei"),
        '左' to listOf("zuo"),
        '右' to listOf("you"),
        '山' to listOf("shan"),
        '河' to listOf("he"),
        '天' to listOf("tian"),
        '地' to listOf("di"),
        '花' to listOf("hua"),
        '鸟' to listOf("niao"),
        '鱼' to listOf("yu"),
        '虫' to listOf("chong"),
        '树' to listOf("shu"),
        '草' to listOf("cao"),
        '红' to listOf("hong"),
        '绿' to listOf("lv"),
        '蓝' to listOf("lan"),
        '白' to listOf("bai"),
        '黑' to listOf("hei"),
        '黄' to listOf("huang"),
        '金' to listOf("jin"),
        '银' to listOf("yin"),
        '铜' to listOf("tong"),
        '铁' to listOf("tie"),
        '爱' to listOf("ai"),
        '好' to listOf("hao"),
        '美' to listOf("mei"),
        '丽' to listOf("li"),
        '快' to listOf("kuai"),
        '乐' to listOf("le"),
        '新' to listOf("xin"),
        '旧' to listOf("jiu"),
        '友' to listOf("you"),
        '朋' to listOf("peng"),
        '工' to listOf("gong"),
        '作' to listOf("zuo"),
        '学' to listOf("xue"),
        '习' to listOf("xi"),
        '吃' to listOf("chi"),
        '喝' to listOf("he"),
        '穿' to listOf("chuan"),
        '住' to listOf("zhu"),
        '行' to listOf("xing"),
        '走' to listOf("zou"),
        '跑' to listOf("pao"),
        '跳' to listOf("tiao"),
        '睡' to listOf("shui"),
        '醒' to listOf("xing"),
        '笑' to listOf("xiao"),
        '哭' to listOf("ku"),
        '唱' to listOf("chang"),
        '舞' to listOf("wu"),
        '书' to listOf("shu"),
        '本' to listOf("ben"),
        '笔' to listOf("bi"),
        '纸' to listOf("zhi"),
        '桌' to listOf("zhuo"),
        '椅' to listOf("yi"),
        '床' to listOf("chuang"),
        '房' to listOf("fang"),
        '门' to listOf("men"),
        '窗' to listOf("chuang"),
        '车' to listOf("che"),
        '路' to listOf("lu"),
        '桥' to listOf("qiao"),
        '城' to listOf("cheng"),
        '村' to listOf("cun"),
        '镇' to listOf("zhen"),
        '市' to listOf("shi"),
        '省' to listOf("sheng"),
        '国' to listOf("guo"),
        '世' to listOf("shi"),
        '界' to listOf("jie"),
        '地' to listOf("di"),
        '球' to listOf("qiu"),
        '月' to listOf("yue"),
        '星' to listOf("xing"),
        '空' to listOf("kong"),
        '风' to listOf("feng"),
        '雨' to listOf("yu"),
        '雪' to listOf("xue"),
        '雷' to listOf("lei"),
        '电' to listOf("dian"),
        '光' to listOf("guang"),
        '火' to listOf("huo"),
        '冰' to listOf("bing"),
        '热' to listOf("re"),
        '冷' to listOf("leng"),
        '早' to listOf("zao"),
        '晚' to listOf("wan"),
        '今' to listOf("jin"),
        '明' to listOf("ming"),
        '昨' to listOf("zuo"),
        '春' to listOf("chun"),
        '夏' to listOf("xia"),
        '秋' to listOf("qiu"),
        '冬' to listOf("dong"),
        '猫' to listOf("mao"),
        '狗' to listOf("gou"),
        '羊' to listOf("yang"),
        '牛' to listOf("niu"),
        '马' to listOf("ma"),
        '鸡' to listOf("ji"),
        '鸭' to listOf("ya"),
        '鹅' to listOf("e"),
        '猪' to listOf("zhu"),
        '兔' to listOf("tu"),
        '熊' to listOf("xiong"),
        '老' to listOf("lao"),
        '虎' to listOf("hu"),
        '狮' to listOf("shi"),
        '象' to listOf("xiang"),
        '龙' to listOf("long"),
        '凤' to listOf("feng"),
        '照' to listOf("zhao"),
        '片' to listOf("pian"),
        '图' to listOf("tu"),
        '画' to listOf("hua"),
        '相' to listOf("xiang"),
        '机' to listOf("ji"),
        '电' to listOf("dian"),
        '脑' to listOf("nao"),
        '视' to listOf("shi"),
        '频' to listOf("pin"),
        '音' to listOf("yin"),
        '乐' to listOf("yue"),
        '游' to listOf("you"),
        '戏' to listOf("xi"),
        '电' to listOf("dian"),
        '影' to listOf("ying"),
        '动' to listOf("dong"),
        '漫' to listOf("man"),
        '卡' to listOf("ka"),
        '通' to listOf("tong"),
        '体' to listOf("ti"),
        '育' to listOf("yu"),
        '运' to listOf("yun"),
        '动' to listOf("dong"),
        '健' to listOf("jian"),
        '康' to listOf("kang"),
        '医' to listOf("yi"),
        '院' to listOf("yuan"),
        '药' to listOf("yao"),
        '病' to listOf("bing"),
        '痛' to listOf("tong"),
        '累' to listOf("lei"),
        '饿' to listOf("e"),
        '渴' to listOf("ke"),
        '饱' to listOf("bao"),
        '咸' to listOf("xian"),
        '甜' to listOf("tian"),
        '酸' to listOf("suan"),
        '辣' to listOf("la"),
        '苦' to listOf("ku"),
        '香' to listOf("xiang"),
        '臭' to listOf("chou"),
        '软' to listOf("ruan"),
        '硬' to listOf("ying"),
        '粗' to listOf("cu"),
        '细' to listOf("xi"),
        '厚' to listOf("hou"),
        '薄' to listOf("bo"),
        '宽' to listOf("kuan"),
        '窄' to listOf("zhai"),
        '深' to listOf("shen"),
        '浅' to listOf("qian"),
        '远' to listOf("yuan"),
        '近' to listOf("jin"),
        '快' to listOf("kuai"),
        '慢' to listOf("man"),
        '早' to listOf("zao"),
        '迟' to listOf("chi"),
        '忙' to listOf("mang"),
        '闲' to listOf("xian"),
        '富' to listOf("fu"),
        '穷' to listOf("qiong"),
        '贵' to listOf("gui"),
        '便' to listOf("pian"),
        '宜' to listOf("yi")
    )
    
    /**
     * Convert a Chinese text to possible Pinyin representations
     */
    fun toPinyin(text: String): List<String> {
        val result = mutableListOf<String>()
        val fullPinyin = StringBuilder()
        val initialPinyin = StringBuilder()
        
        for (char in text) {
            val pinyinList = chineseToPinyin[char]
            if (pinyinList != null && pinyinList.isNotEmpty()) {
                val pinyin = pinyinList[0] // Use first pronunciation
                fullPinyin.append(pinyin)
                if (pinyin.isNotEmpty()) {
                    initialPinyin.append(pinyin[0])
                }
            } else {
                // For non-Chinese characters, keep original
                fullPinyin.append(char)
                if (char.isLetter()) {
                    initialPinyin.append(char)
                }
            }
        }
        
        // Add original text
        result.add(text.lowercase())
        // Add full pinyin
        if (fullPinyin.toString() != text) {
            result.add(fullPinyin.toString().lowercase())
        }
        // Add initial pinyin
        if (initialPinyin.toString() != text && initialPinyin.toString() != fullPinyin.toString()) {
            result.add(initialPinyin.toString().lowercase())
        }
        
        return result.distinct()
    }
    
    /**
     * Check if a label matches the search query considering Pinyin
     */
    fun matchesSearch(labelName: String, searchQuery: String): Boolean {
        if (searchQuery.isBlank()) return true
        
        val query = searchQuery.lowercase().trim()
        val pinyinVariants = toPinyin(labelName)
        
        return pinyinVariants.any { variant ->
            variant.contains(query)
        }
    }
}